### ISSUE TITLE
Barrels/stacked blocks can be accessed still by other player's.

### ISSUE THREAD

**Issue by InventiveSins** [BONNePlayground/WildStackerHook#2]
#### Describe the bug
Player's can deducte blocks from "STACKED BLOCKS" or "BARRELS" even with this hook from other player's islands.

#### Steps to reproduce the behavior
Get WildStacker...
Enable Wildstacker barrels and add stackable blocks to the config. (we used netherite blocks)
Get the Wildstacker hook.
Get 2 accounts, one make an island, the other, get tp'd to the island of the other account. Make sure not to have any permissions.
Then right-click the blocks that are stacked...

#### Expected behavior
For the plugin disable the event of withdrawing blocks from the Wildstacker Barrel(s).

#### Screenshots and videos (Optional)
https://youtu.be/vPmUffK7ZcM

### Environment
Paperspigot 1.18.2

##### BentoBox Version (Mandatory)
![image](https://user-images.githubusercontent.com/87890013/180113148-53735e1a-cdf2-4cef-8cdf-ce1be98cff20.png)

_______
```

#### Plugins (Optional)
Essentials, Vault, Wildstacker, Bentobox, Papi
```
_______
```
 
### Additional context (Optional)
<!-- Any additional information you'd like to provide us. -->
<!-- Please type below this line. -->

**Comment by InventiveSins** [comment]
Hoping this can get looked into ASAP. We've got many islands with thousands of stacked blocks. It'd literally hurt the server if we have to remove wildstacker entirely.

**Comment by BONNe** [comment]
Did not know that wildstacker had such a feature. It was not documented everywhere.

I do not use any stackers myself. Thanks for reporting.

The issue should be fixed in 1.2.0-DEV

**Comment by InventiveSins** [comment]
Thank you for the hastey fix! I appreciate it.

**Comment by InventiveSins** [comment]
> Did not know that wildstacker had such a feature. It was not documented everywhere.
> 
> I do not use any stackers myself. Thanks for reporting.
> 
> The issue should be fixed in 1.2.0-DEV

Where can I get 1.2.0 DEV? I don't see it in the original download of github.

**Comment by BONNe** [comment]
https://ci.codemc.io/job/BONNePlayground/job/WildStackerHook/

**Comment by InventiveSins** [comment]
> https://ci.codemc.io/job/BONNePlayground/job/WildStackerHook/

Tysm!
